version: "3.4"

services:
###> symfony/mailer ###
  mailer:
    image: maildev/maildev
    ports: ["1025", "1080"]
###< symfony/mailer ###

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123123}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
        ###< doctrine/doctrine-bundle ###

volumes:


###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
