<?php

namespace App\Model;

enum Mountain: string
{
    case ANDORRE = 'ANDORRE';
    case ARAVIS = 'ARAVIS';
    case ASPEOSSAU = 'ASPE-OSSAU';
    case AURELOURON = 'AURE-LOURON';
    case BAUGES = 'BAUGES';
    case BEAUFORTAIN = 'BEAUFORTAIN';
    case BELLEDONNE = 'BELLEDONNE';
    case CAPCIRPUYMORENS = 'CAPCIR-PUYMORENS';
    case CERDAGNECANIGOU = 'CERDAGNE-CANIGOU';
    case CHABLAIS = 'CHABLAIS';
    case CHAMPSAUR = 'CHAMPSAUR';
    case CHARTREUSE = 'CHARTREUSE';
    case CINTOROTONDO = 'CINTO-ROTONDO';
    case COUSERANS = 'COUSERANS';
    case DEVOLUY = 'DEVOLUY';
    case EMBRUNAISPARPAILLON = 'EMBRUNAIS-PARPAILLON';
    case GRANDESROUSSES = 'GRANDES-ROUSSES';
    case HAUTVAR_HAUTVERDON = 'HAUT-VAR_HAUT-VERDON';
    case HAUTEARIEGE = 'HAUTE-ARIEGE';
    case HAUTEBIGORRE = 'HAUTE-BIGORRE';
    case HAUTEMAURIENNE = 'HAUTE-MAURIENNE';
    case HAUTETARENTAISE = 'HAUTE-TARENTAISE';
    case LUCHONNAIS = 'LUCHONNAIS';
    case MAURIENNE = 'MAURIENNE';
    case MERCANTOUR = 'MERCANTOUR';
    case MONTBLANC = 'MONT-BLANC';
    case OISANS = 'OISANS';
    case ORLU__ST_BARTHELEMY = 'ORLU__ST_BARTHELEMY';
    case PAYSBASQUE = 'PAYS-BASQUE';
    case PELVOUX = 'PELVOUX';
    case QUEYRAS = 'QUEYRAS';
    case RENOSOINCUDINE = 'RENOSO-INCUDINE';
    case THABOR = 'THABOR';
    case UBAYE = 'UBAYE';
    case VANOISE = 'VANOISE';
    case VERCORS = 'VERCORS';
}
